language: php
php:
  - '7.2'
  - '7.3'
  - nightly

before_script:
  - cp WorkTimeLoggerServer/.env.travis WorkTimeLoggerServer/.env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - cd WorkTimeLoggerServer && composer install --no-interaction
  - cd WorkTimeLoggerServer && php artisan key:generate
  - cd WorkTimeLoggerServer && php artisan migrate

script:
  - WorkTimeLoggerServer/vendor/bin/phpunit