//
// Created by Krystian Duma on 2019-02-27.
//

#ifndef WORKTIMELOGGERFIRMWAREFORATMEGA328_USART_H
#define WORKTIMELOGGERFIRMWAREFORATMEGA328_USART_H

#endif //WORKTIMELOGGERFIRMWAREFORATMEGA328_USART_H
